combat-length: 15 # (in seconds)
# freeBar timeout
vanish-timeout: 5 # (in seconds)

bossbar:
  enable-bar: true
  # Here you can use these colors: blue, green, pink, purple, red, white and yellow.
  busy-color: red
  free-color: green

  # Here you can use these styles: solid, segmented_6, segmented_10, segmented_12 and segmented_20.
  busy-style: segmented_6
  free-style: solid

  # Here you can use these placeholders: {displayname}, {username}, {timeleft} and {timeout}.
  # '&' is used in place of the Minecraft default 'ยง'; Formatting guide:  https://minecraft.fandom.com/wiki/Formatting_codes
  busy-message: '&cDo not log out before&7: &r{timeleft} secs.'
  free-message: '&aYou can now log out'

chat:
  # Here you can use these placeholders: {displayname}, {username}, {timeleft} and {timeout}.
  # '&' is used in place of the Minecraft default 'ยง'; Formatting guide:  https://minecraft.fandom.com/wiki/Formatting_codes
  broadcast-message: '&b[AntiRelog] &6Player &2{displayname} &6has left while in combat!'
  # You can opt out of sending each of the following messages by settings them to an empty string.
  busy-chat: '&c[AntiRelog] &fYou are now in &6combat&f! It time out in {timeout} seconds.'
  free-chat: '&a[AntiRelog] &6Combat&f timed out!'

# Minecraft entity types:  https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/EntityType.html
# The list below defines which types of entities are capable of engaging players in combat.
# 'ALL' matches all types of entities.
subjects:
  - ALL
