combat-length: 15
vanish-timeout: 5

bar:
  enable-bar: true
  # Here you can use only this colors: blue, green, pink, purple, red, white, yellow
  busy-color: red
  free-color: green

  # Here you can use only this styles: solid, segmented_6, segmented_10, segmented_12, segmented_20
  busy-style: segmented_6
  free-style: solid

  # Here you can use only this placeholders: {displayname}, {username}, {timeleft}, {timeout}
  # '&' is replace 'ยง' if you use minecraft formatting https://minecraft.fandom.com/wiki/Formatting_codes
  busy-message: '&cDo not log out before&7: &r{timeleft} secs.'
  free-message: '&aYou can now log out'

chat:
  # '&' is replace 'ยง' if you use minecraft formatting https://minecraft.fandom.com/wiki/Formatting_codes
  broadcast-message: '&b[AntiRelog] &6Player &2{displayname} &6has left while in combat!'
  # When you set(leave?) one from this messages below empty, it don't send
  busy-chat: '&c[AntiRelog] &fYou are now in &6combat&f! It time out in {timeout} seconds.'
  free-chat: '&a[AntiRelog] &6Combat&f timed out!'

subjects:
  - Player
  - Zombie
  - Husk
  - Zombie_Villager