name: AntiRelog
author: 'Jeremiasz N. <remi6397 gmail com>'
version: @VERSION@
api-version: '1.16'
main: pl.jeremi.antirelog.AntiRelog
permissions:
  antirelog.*:
    description: Get access to all functions of AntiRelog.
    default: op
    children:
      antirelog.reload: true
      antirelog.bypass: true
  antirelog.reload:
    description: Reload Anti-Relog config.
    default: op
  antirelog.bypass:
    description: Bypass Anti-Relog protection.
    default: op
commands:
  arreload:
    description: AntiRelog reload config
    permission: antirelog.reload
