name: AntiRelog
author: 'Jeremiasz N. <remi6397 gmail com>'
version: @VERSION@
api-version: '1.16'
main: pl.jeremi.antirelog.AntiRelog
permissions:
  antirelog.*:
    description: Get access to all functions of AntiRelog.
    default: op
    children:
      antirelog.bypass: true
      antirelog.toggle: true
      antirelog.toggle.others: true
  antirelog.bypass:
    description: Bypass Anti-Relog protection.
    default: op
  antirelog.toggle:
    description: Toggle AntiRelog bypass.
    default: op
  antirelog.toggle.others:
    description: Toggle AntiRelog bypass for other players.
    default: op
    children:
      antirelog.toggle: true
commands:
  artoggle:
    description: AntiRelog main command
    permission: antirelog.toggle
    permission-message: "[AntiRelog] You don't have permission to do that!"
    usage: |
      AntiRelog by Jeremi
      /artoggle [player]
